title: "Eng. Rashid Ongoma"
email: "rashidongoma@gmail.com"
description: >-
  Main Developer at Kuku Predikt and Soma Smart | Researcher | Consultant | Author
baseurl: ""
twitter_username: youngdevelopa
github_username: youngdevelopa
minimal_mistakes_skin: plum
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/
paginate: 3
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author information
author:
  name   : "Eng. Rashid Ongoma"
  avatar : "/assets/images/RashidPassport.jpg"
  bio    : "Engineer | Software Developer (Django/Kotlin) | Founder of Kuku Predikt | Author & Consultant"
  location: "Nairobi, Kenya"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=CLzA3BQAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rashid-ongoma-49a15917b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/youngdevelopa/"
    - label: "Cyber Shujaa"
      icon: "fas fa-fw fa-shield-alt"
      url: "https://cybershujaa.co.ke/"

# Footer social links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rashid-ongoma-49a15917b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/youngdevelopa/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=CLzA3BQAAAAJ&hl=en"

# Default values
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
